# -*- coding: utf-8 -*-
"""Curso Linguagem de Programação - Nélio Alvez

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14jjnyN8JKiOK-rXcuIEKtE_Kut6aY3P1

Exercício - 27
* Verificação de Senha Numérica
"""

# peça para o usuário criar uma senha numérica
senhacriada = int(input("Crie uma senha apenas com números: "))

# imprima uma mensagem para o usuário informar a senha criada
senha = int(input("Digite a senha: "))

# enquanto a senha for diferente da senha criada
while senha != senhacriada:
    # senha invalida
    print("Senha Invalida! Tente novamente:")

    # digite novamente
    senha = int(input("Digite a senha: "))

# senão for diferente informe acesso permitido.    
print("Acesso Permitido!")

"""Exercício - 26
* Calculando a média de várias idades
"""

# variavel
idade = int(input("Digite as idades: "))
soma = 0
quantidade = 0
# enquanto idade for maior que 0
while idade > 0:
    # soma a idade existente + a idade atual
    soma += idade
    # a quantidade recebe a quantidade anterior + 1
    quantidade += 1
    # a média é a divisão da soma das idades pela quantidade de idades informadas
    media = soma / quantidade
    # peça para o usuário digitar outra idade
    idade = int(input("Digite outra idade: "))
    # se a idade for menor que 0 encerre o programa e mostre na tela a média
    if idade < 0:
        print("MEDIA = {:.2f}".format(media))
# caso a média seja igual a 0 diga para o usuário que é impossivel calcular
if media == 0:
    print("IMPOSSIVEL CALCULAR")

"""Exercício - 25 
* Verificador de ordem de números
"""

print("Digite dois números:")
x = input()
y = input()

while x != y:
   if x > y:
      print("DECRESCENTE!")
   else:
      print("CRESCENTE!")
   
   print("Digite outros dois números:")
   x = input()
   y = input()

"""Exercício - 24
* Identificação de Quadrante e Eixo Cartesiano
"""

x = float(input("Valor de X: "))
y = float(input("Valor de Y: "))

if x > 0 and y > 0:
    print("Q1")
elif x < 0 and y > 0:
    print("Q2")
elif x < 0 and y < 0:
    print("Q3")
elif x > 0 and y < 0:
    print("Q4")
elif x == 0 and y == 0:
    print("Origem")
elif x == 0 and y != 0:
    print("Eixo Y")
else:
    print("Eixo X")

"""Exercício - 23
* Cálculo de tempo de jogo.
"""

inicial = int(input("Hora inicial: "))
final = int(input("Hora final: "))

if inicial < final:
    duracao = final - inicial
else:
    duracao = 24 - inicial + final

print("O jogo durou ", duracao, "hora(s)")

"""Exercício - 22
* Cálculo de aumento de salário.
"""

salario = float(input("Digite o salario da pessoa: "))

if salario <= 1000:
    porcentagem = 20
elif salario <= 3000:
    porcentagem = 15
elif salario <= 8000:
    porcentagem = 10
else:
    porcentagem = 5

aumento = (salario * porcentagem) / 100
novo_salario = salario + aumento

print("Novo salario = R$ {:.2f}".format(novo_salario))
print("Aumento = R$ {:.2f}".format(aumento))
print("Porcentagem = {}%".format(porcentagem))

"""Exercício - 21 
* Verificação de múltiplos entre dois números inteiros.
"""

a = int(input("Digite um número inteiro: "))
b = int(input("Digite outro número inteiro: "))

if a % b == 0 or b % a == 0:
    print("São múltiplos")
else:
    print("Não são múltiplos")

"""Exercício - 20 
* Cálculo de valor a pagar em uma lanchonete
"""

codigo = float(input("Insira o código do produto comprado: "))

if codigo == 1:
    codigo = 5.00
elif codigo == 2:
    codigo = 3.50
elif codigo == 3:
    codigo = 4.80
elif codigo == 4:
    codigo = 8.90
elif codigo == 5:
    codigo = 7.32
else:
    codigo = "valor inválido"

quantidade = int(input("Quantidade comprada: "))
valor = codigo * quantidade

if codigo == "valor inválido":
    print("Código de produto inválido")
else:
    print("Valor a pagar: R$ {:.2f}".format(valor))

"""Exercício - 19 
* Conversor de temperatura
"""

escala = input("Você vai digitar a temperatura em qual escala (C/F)? ")

if escala.lower() == "f":
    valor = float(input("Digite a temperatura em Fahrenheit: "))
    c = (5 / 9) * (valor - 32)
    print("Temperatura equivalente em Celsius: {:.2f}".format(c))
else:
    valor = float(input("Digite a temperatura em Celsius: "))
    f = (9 / 5) * valor + 32
    print("Temperatura equivalente em Fahrenheit: {:.2f}".format(f))

"""Exercício - 18 
* Encontrando a maior distância 
"""

print("Digite as tres distancias : ")
a = float(input())
b = float(input())
c = float(input())

if (a > b) and (a > c):
    maior = a
elif b > c:
    maior = b
else: maior = c

print("MAIOR DISTANCIA = {:.2f}".format(maior))

"""Exercício - 17 
* Verificação do nível de glicose e classificação em NORMAL, ELEVADO ou DIABETES.
"""

def glicose():
  media = float(input("Digite a medida da glicose: "))

  if media <= 100:
    print("NORMAL")
  elif media > 100 and media <= 140:
    print("ELEVADO")
  elif media > 140:
    print("DIABETES")

glicose()

"""Exercício-16
* Cálculo de Troco em uma Compra
"""

preco = float(input("Preço unitário do produto: "))
quantidade = int(input("Quantidade comprada: "))
dinheiro = float(input("Dinheiro recebido: "))

valor_compra = preco * quantidade
troco = dinheiro - valor_compra

if troco >= 0:
    print("Troco: R$ {:.2f}".format(troco))
else:
    print("Dinheiro insuficiente. Faltam R$ {:.2f}".format(-troco))

"""Exercício - 15
* Cálculo do Valor a Pagar pela Operadora de Telefonia
"""

minutos = int(input("Digite a quantidade de minutos: "))

valor_pago = 50.00

if minutos > 100:
    valor_pago += 2 * (minutos - 100)

print("Valor a pagar: R$ {:.2f}".format(valor_pago))

"""Exercício - 14 
* Encontrar o Menor de Três Números
"""

a = int(input("Primeiro valor: "))
b = int(input("Segundo valor: "))
c = int(input("Terceiro valor: "))

if a < b and a < c:
    menor = a
else:
    if b < c:
        menor = b
    else:
        menor = c

print("Menor =", menor)

"""Exercício - 13 
* Equação de Segundo Grau (BASKARA)
"""

a = float(input("Coeficiente a: "))
b = float(input("Coeficiente b: "))
c = float(input("Coeficiente c: "))

delta = b**2 - 4 * a * c

if a == 0 or delta < 0:
    print("Esta equação não possui raízes.")
else:
    x1 = (-b + delta**0.5) / (2 * a)
    x2 = (-b - delta**0.5) / (2 * a)

    print("X1 =", x1)
    print("X2 =", x2)

"""Exercício - 12 
* Cálculo de Aprovação com Base em Notas
"""

nota1 = int(input("Digite a primeira nota: "))
nota2 = int(input("Digite a segunda nota: "))

total = nota1 + nota2

if total < 60:
    print("REPROVADO")
elif total >= 60:
    print("APROVADO")

print("Nota Final = ", format(total,'.1f'))

"""Exercício - 11
* Conversor de Segundos para Horas, Minutos e Segundos
"""

duracao = int(input("Digite a duracao em segundos: "))

horas = duracao / 3600
resto = duracao % 3600
minutos = resto / 60
segundos = resto % 60

print("Horas: ", format(horas, ".2f"))
print("Minutos: ", format(minutos, ".0f"))
print("Segundos: ", format(segundos, ".0f"))

"""Exercício - 10
* Algoritmo para Cálculo de Áreas de Figuras Geométricas
"""

a = float(input("Digite a medida A: "))
b = float(input("Digite a medida B: "))
c = float(input("Digite a medida C: "))

areaQuadrado = (a * a)
areaTriangulo = (a * b) / 2
areaTrapezio = (a + b) / 2 * c

print("Area do quadrado = ", format(areaQuadrado, '4f'))
print("Area do Triangulo = ", format(areaTriangulo, '4f'))
print("Area do Trapezio = ", format(areaTrapezio, '4f'))

"""Exercício - 9
* Calculo de Consumo de Combustível
"""

distancia = int(input("Distancia percorrida: "))
gasto = float(input("Combustível gasto: "))
consumo = - distancia / gasto

print("Consumo médio = ", format(consumo, '.3f'))

"""Exercício - 8
* Cálculo de pagamento de funcionário
"""

nome = str(input("Nome: "))
valor = float(input("Valor por hora: "))
horas = int(input("Horas trabalhadas: "))
pagamento = valor * horas

print("O pagamento para ",nome," deve ser R$: ",pagamento)

"""Exercício - 7
* Cálculo da Área de um Círculo
"""

import math

raio = float(input("Digite o valor do raio do circulo: "))

area = math.pi * (raio**2)

print("Area: {:.3f}".format(area))

"""Exercício - 6 
* Cálculo de Troco
"""

preço = float(input("Preço unitário do produto: "))
quantidade = int(input("Quantidade comprada: "))
recebido = float(input("Dinheiro recebido: "))

troco = recebido - (preço * quantidade)

print("TROCO = ",troco)

"""Exercício - 5 
* Soma de dois números inteiros
"""

x = int(input("Digite o valor de x: "))
y = int(input("Digite o valor de y: "))
soma = x + y 
print("Soma = ",soma)

"""Exercício - 4
* Cálculo da idade média de duas pessoas
"""

nome1 = input("Dados da primeira pessoa : \nNome: ")
idade1 = int(input("Idade: "))

nome2 = input("Dados da segunda pessoa : \nNome: ")
idade2 = int(input("Idade: "))

media = (idade1 + idade2) / 2

print("A idade média de ", nome1," e ", nome2 ," é de ", round(media, 1), " anos ")

"""Exercício - 3 
* Cálculo de Área, Perímetro e Diagonal de um Retângulo
"""

base = float(input("Base do retangulo: "))
altura = float(input("Altura do retangulo: "))

area = base * altura
perimetro = (base + altura) * 2
diagonal = (base**2 + altura**2)**0.5

print("Area = ", area)
print("Perimetro = ", perimetro)
print("Diagonal = ", diagonal)

"""Exercício - 2
* Descubra o tamanho do terreno
"""

largura = float(input("Digite a largura do terreno: "))
comprimento = float(input("Digite o comprimento do terreno: "))
metroQuadrado = float(input("Digite o valor do metro quadrado: "))

area = largura * comprimento
preco = area * metroQuadrado

print("Area do terreno = ", area)
print("Preco do terreno = ", preco)

"""Exercício - 1
* Imprimindo valores na tela
"""

produto1 = "Computador "
preco1 = 2100.5
produto2 = "TV "
preco2 = 1830.0
codigo = 5291
genero = "F "
idade = 30

print("Produtos: ")
print("O produto ",produto1," custa R$ ",preco1)
print("O produto ",produto2," custa R$ ",preco2)
print()
print("Codigo =",codigo)
print()
print("Dados da pessoa: ","genero ", genero,"e idade ",idade)